CMSgov/ab2d

README.md

Minor refinement to the docker-compose command in README
I got an error, when I checked out the repository and ran the docker-compose command listed in the README.  For my first PR, updating the README to the pass the `--build` argument to the `docker-compose` command. No code changes
N/A

refine docker-compose command in readme

---

api/pom.xml
api/src/test/resources/application.properties
domain/pom.xml
domain/src/main/resources/application.properties
pom.xml

Upgrade spring boot to 2.2
Upgrade application to use the current version of spring-boot (2.2) -which includes junit5 and some performance improvement and upgrades to the numerous dependencies that spring-boot manages.
N/A
N/A

Upgrade spring boot

---

docker-compose.yml

Set the postgres version to 11 in the docker-compose file used for local development
Since Amazon Aurora does not support the latest version of PostgreSQL (12) as of today, we should specify the version number of the postgres image in the docker-compose file used for local development.
N/A
N/A
N/A

set postgres to version 11 in docker-compose

---

api/src/test/resources/application.properties
domain/src/main/java/gov/cms/ab2d/domain/Job.java
domain/src/main/java/gov/cms/ab2d/domain/JobOutput.java
domain/src/main/java/gov/cms/ab2d/domain/User.java

Add missing `@JoinColumn` on  `@ManyToOne` associations.
A few of the `@ManyToOne` associations are missing the `@JoinColumn`.  
Adding it for completeness.
N/A
N/A

Add missing JoinColumn annotations

---

domain/src/main/java/gov/cms/ab2d/domain/User.java

Rename user table to user_account table as user is a reserved keyword in PG SQL
`user` is a reserved keyword in postgres and SQL so renaming the table to remove any ambiguity and awkwardness while querying the table.
https://www.postgresql.org/docs/10/sql-keywords-appendix.html
N/A
N/A

Rename user table to user_account table

---

api/src/main/java/gov/cms/ab2d/api/controller/BulkDataAccessAPI.java
api/src/main/java/gov/cms/ab2d/api/service/JobServiceImpl.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/service/JobServiceTest.java
domain/src/main/java/gov/cms/ab2d/domain/Attestation.java
domain/src/main/java/gov/cms/ab2d/domain/Job.java

Use OffsetDateTime for timestamp instead of LocalDateTime
LocalDateTime does not have the offset related to the timezone needed in a timestamp.
A Timestamp only makes sense when it has an offset from UTC or a zone Id.
Java provides OffsetDateTime for the `TIMESTAMPTZ` data type provided by Postgres which translates to a columnDefinition of `TIMESTAMP WITH TIME ZONE` for  H2
N/A
N/A

Use OffsetDateTime for timestamp

---

api/src/test/resources/application.properties
domain/src/test/resources/application.properties

Set PostgreSQL compatibility mode for H2
Set postgres compatibility mode for H2 during test
http://h2database.com/html/features.html#compatibility
N/A
N/A

set postgres compatibility mode for H2 during test

---

worker/pom.xml
worker/src/main/java/gov/cms/ab2d/worker/SpringBootApp.java
worker/src/main/java/gov/cms/ab2d/worker/config/WorkerConfig.java

Add `BFD` dependency to `worker` module
The worker module would need to use the BFD  client to get the Explanations of Benefit associated with a given patient id from BB. So need to incorporate the `bfd` module as a dependency in the worker module.
Also, since the configuration for BFD beans is not defined in the worker module, the bdf bean configuration needs to be imported into the worker bean configuration file.
N/A
N/A

Add bfd dependency to worker module

---

api/src/main/resources/application.properties
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/resources/application.properties
common/src/main/java/gov/cms/ab2d/common/service/UserServiceImpl.java
common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v001/AB2D-291-create-initial-tables.sql
common/src/main/resources/db/changelog/v001/AB2D-331-drop-constraint-add-column.sql
common/src/main/resources/db/changelog/v001/AB2D-356-rename-columns.sql
common/src/test/java/gov/cms/ab2d/common/service/JobServiceTest.java
common/src/test/resources/application.common.properties
hpms/src/test/java/gov/cms/ab2d/hpms/processing/AttestationReportProcessorTests.java
hpms/src/test/java/gov/cms/ab2d/hpms/processing/OrgStructureReportProcessorTests.java
hpms/src/test/resources/application.hpms.properties
hpms/src/test/resources/hpms-it.properties
worker/src/test/resources/application.properties

Liquibase, not Hibernate's auto-DDL, should run in tests as well.
All of the integration tests now run the actual Liquibase migrations to prep the database instead of relying on the DDL auto-generation. This ensures the tests execute against exactly the same schema that is used in the environments. The underlying database in tests is still H2 though (albeit in PostgreSQL-compatibility mode): we'll need to think about switching to Test Containers eventually.
N/A
N/A

AB2D-373: Liquibase, not Hibernate's auto-DDL, should run in tests as well

---

worker/pom.xml
worker/src/main/java/gov/cms/ab2d/worker/service/JobProcessingServiceImpl.java
worker/src/test/java/gov/cms/ab2d/worker/service/JobProcessingServiceTest.java

Upon completion of the job, set the value for  Job CompletedAt.
Also, adjust the logging statement to use job_uuid instead of jobId
Upon completion of the job, set the value for  Job CompletedAt.
Also, adjust the logging statement to use job_uuid instead of jobId
N/A
N/A

set job completedAt & use jobUuid while logging

---

worker/src/main/java/gov/cms/ab2d/worker/service/JobProcessingServiceImpl.java
worker/src/main/resources/application.properties

Modified the Worker to write only the file name into `JobOutput.filePath`to match the API's expectations.
Modified the Worker to write only the file name into `JobOutput.filePath`to match the API's expectations. The API is unable to download the files otherwise. 
NA

Modified the Worker to write only the file name into JobOutput.filePath

---

worker/src/main/java/gov/cms/ab2d/worker/service/FileService.java
worker/src/test/java/gov/cms/ab2d/worker/service/FileServiceIntegrationTest.java

When output files already exist when a job executes, delete it and create a new file during the job execution
During the execution of the job, if the output files already exist, delete them. This would happen when a job ends in a failure and it needs to be restarted
N/A
N/A

When output files already exist, delete it and create new ones during the job execution

---

.github/workflows/trufflehog_github_actions.yml

Correcting URL for excludes fetch. it was missing "master" in the URL to specify the branch in the original implementation from PR #72 
This builds off of PR #72 to correct a bug that was caused by an incorrect URL being provided for excludes.

AB2D-498 Correcting URL for excludes fetch

---

trufflehog-excludes.txt

Additional excludes to tune out false positives in secrets scanning automation for trufflehog. Current scans pick up high entropy strings that are not secrets but are either public keys or integrity hashes/test data. These have been analyzed and added to the excludes file in the root of the repo with this PR.
This does remove some files from view of the scanner in an effort to reduce false positives. This means if someone commits a secret to an excluded file/directory, it could be ignored. That said, this is a low risk because only authorized users should be able to commit code, and each PR is reviewed manually. If someone intentionally hid a secret into an excluded directory this would constitute as an …

AB2D-498 Additional excludes to tune out false positives

---

trufflehog-excludes.txt

New false positive was reported by a commit to the branch:
`feature/ab2d-355-automate-aws-waf-and-shield-configuration-deployment`
This PR filters out all authorized_keys entries with regex and filters additional false positives that were identified during analysis of the results. We won't be able to exclude every file that comes along, but this one highlighted a key area where we can drastically reduce false positives that flag on authorized keys and is worth updating our excludes for.
This improves the security posture of the code base by reducing false positives for our secrets scanner. Public keys like authorized_keys are high entropy strings, but are not secret and do not need to be alerted on.

AB2D-498 Filter out all authorized_keys entries with regex

---

trufflehog-excludes.txt

The original fix included with PR #78 had a regular expression that only tested for directories nested 1 folder deep. This new regex contains no directory constraints and checks for all instances of the authorized keys file.
Fixes the security regression caused by a bad regex in PR #78, impact is the same as the original PR #78

AB2D 498 Regex Secrets Filter

---

optout/src/main/java/gov/cms/ab2d/optout/setup/OptOutQuartzSetup.java
worker/src/main/java/gov/cms/ab2d/worker/SpringBootApp.java

rename QuartzJob to OptOutQuartzJob to fix duplicate bean name
rename QuartzJob to OptOutQuartzJob to fix duplicate bean name
N/A
N/A

rename QuartzJob to OptOutQuartzJob to fix duplicate bean name

---

common/src/main/java/gov/cms/ab2d/common/repository/JobRepository.java
worker/src/main/java/gov/cms/ab2d/worker/service/JobCancelledException.java
worker/src/main/java/gov/cms/ab2d/worker/service/JobProcessingServiceImpl.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/service/JobProcessingServiceUnitTest.java
worker/src/test/resources/application.properties

Add functionality to the worker module to enable it to stop processing an `IN_PROGRESS` job mid-way if the job gets cancelled
While the working is processing a submitted job, if the job gets cancelled, the worker needs to be aware of it and attempt to cancel the  processing of the job, if possible.
N/A
N/A

AB2D 609 handle job cancellation in worker

---

audit/src/main/java/gov/cms/ab2d/audit/cleanup/FileDeletionJob.java
audit/src/main/resources/application.audit.properties
optout/src/main/java/gov/cms/ab2d/optout/job/OptoutJob.java
optout/src/main/resources/application.optout.properties

prevent concurrent execution of quartz job in worker
Occasionally, when the worker is started, it appeared as if the opt-out was being triggered twice concurrently on start-up for the first run. Adding an extra configuration to prevent it.
N/A
N/A

prevent concurrent execution of quartz job in worker

---

common/src/main/resources/application.common.properties
docker-compose.yml
optout/src/main/resources/application.optout.properties

Added additional environment variables to support Dev/Sandbox roll-out
Added environment variables that will hold EFS mount and opt-out file S3 location information with default fallback to values that would work in Dex or Sandbox. Update Dockerfile to call them out explicitly. 
N/A

Added additional environment variables to support Dev/Sandbox roll-out

---

lgtm.yml

The AB2D project is upgrading to Java 13, and as such the LGTM config needs to be reconfigured to use Java 13 instead of Java 12. This PR updates the lgtm config to build with Java 13.
This helps maintain our current security posture by insuring LGTM is configured correctly so it can continue to build the project and perform SAST scans.

AB2D-660 Upgrade lgtm config to build with Java 13

---

lgtm.yml

LGTM config to fix java and maven build versions for jdk13. Our previous builds were failing due to what `appeared` to be a version mismatch on the LGTM service with JDK. It ended up being resolved by specifying the correct maven version that was working when building locally which at the time of this PR should be the latest `3.6.3`.
This improves the security posture by fixing a breaking build bug that was revealed during our JDK13 upgrade preventing automated SAST. Now SAST will be able to resume as part of the regular SDLC.

lgtm config to fix java and maven build versions for jdk13

---

worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/service/FileServiceImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/FileServiceIntegrationTest.java

When a batch needs to be restarted after a failure, the output directory needs to be re-created afresh
When a job is submitted, the batch process creates an output directory based on the job_uuid.
Inside this directory, it will create an ndjson file for each contract for the sponsor who submitted the job.
So normally the output directory would not exist prior to the start of the batch process.
However, when a batch is restarted after a failure, the output directory would already exist (from the failed run) and it needs to be deleted and re-created afresh
N/A
N/A

ab2d 685 delete pre existing job directory

---

worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorUnitTest.java

When a job is cancelled, delete the output directory created by the cancelled job and the partially created import files 
When a job is cancelled, the worker would stop the import process in an orderly fashion. It was concluded that the (partial) import files created should also be cleaned up after stopping the processing. This PR refines the process to also delete the output directory created by the cancelled job along the files created within it.
N/A
N/A

ab2d 686 delete files on job cancellation

---

bfd/pom.xml
bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
bfd/src/main/resources/application.bfd.properties
bfd/src/test/resources/application.bfd.properties
worker/src/main/java/gov/cms/ab2d/worker/SpringBootApp.java
worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java

Retry failed bfd calls
When worker makes a call to BFD, since it is a remote call, it could fail due to intermittent errors.
In these cases, a retry should be attempted for failed calls. The configuration for retry should be externalized in a property file. Spring-retry module was used to accomplish the retry
N/A
N/A

AB2D 675 - retry failed bfd calls

---

bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClient.java
bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientTest.java

Do not throw exception when patient has no claims data
Do not throw exception when patient has no claims data. 
N/A
N/A

ab2d 746 - do not throw exception when patient has no claims data

---

website/404.html
website/Gemfile
website/_config.yml
website/hidden/faq.md
website/index.md

Because I began work on the FAQ, wanted to make sure it wasn't on some remote branch that we would forget
I created a directory /hidden/ that is not linked to anywhere and placed the FAQ info in that directory. Because you could browse that directory, I also removed that ability and if you try to browse that directory, it gives you a 404.
You can still access the file by putting in /hidden/faq but you have no way to find it without knowing it's there.

Created a FAQ in a hidden directory removed the ability to browse that dir

---

common/src/main/java/gov/cms/ab2d/common/repository/JobRepository.java
worker/src/main/java/gov/cms/ab2d/worker/config/WorkerConfig.java
worker/src/main/java/gov/cms/ab2d/worker/service/ShutDownService.java
worker/src/main/java/gov/cms/ab2d/worker/service/ShutDownServiceImpl.java
worker/src/main/java/gov/cms/ab2d/worker/service/WorkerServiceImpl.java

When a shutdown command is issued, worker needs to put active jobs into submitted status
When a shutdown command is issued, worker needs to put active jobs into submitted status so that the job can be processed by another instance.
N/A
N/A

ab2d 667 shutdown cleanup reset jobs

---

api/src/main/java/gov/cms/ab2d/api/config/SwaggerConfig.java
api/src/main/java/gov/cms/ab2d/api/controller/BulkDataAccessAPI.java
api/src/main/java/gov/cms/ab2d/api/security/SecurityConfig.java
api/src/main/java/gov/cms/ab2d/api/util/Constants.java
api/src/main/java/gov/cms/ab2d/api/util/SwaggerConstants.java
api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIUserTests.java
api/src/test/java/gov/cms/ab2d/api/controller/AuthenticationTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIUnusualDataTests.java
api/src/test/java/gov/cms/ab2d/api/controller/InvalidTokenTest.java
api/src/test/java/gov/cms/ab2d/api/controller/RoleTests.java
common/src/main/java/gov/cms/ab2d/common/model/Job.java
common/src/main/java/gov/cms/ab2d/common/util/Constants.java
common/src/test/java/gov/cms/ab2d/common/service/JobServiceTest.java
filter/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmer.java
filter/src/test/java/gov/cms/ab2d/filter/EOBLoadUtilitiesTest.java
filter/src/test/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerTest.java
worker/src/main/java/gov/cms/ab2d/worker/adapter/bluebutton/PatientClaimsProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/PatientClaimsProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/WorkerServiceTest.java

Cleaned up the Swagger documentation 
- Added constants for reused values and to remove the 
bulk of the text out of the file. 
- Created defaults for situations where only one value is allowed
- Expanded on some of the text
- Changed ExplanationOfBenefits to ExplanationOfBenefit since that is the name of the object throughout the system and made it a variable to prevent typos.
- Because there was a static variable with the same value SPONSOR in common, used that one instead of the one in api.
No security implications

Ab2d 742 improve swagger docs

---

api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
audit/src/test/java/gov/cms/ab2d/audit/cleanup/FileDeletionServiceTest.java
common/src/main/java/gov/cms/ab2d/common/service/JobServiceImpl.java
common/src/test/java/gov/cms/ab2d/common/service/JobServiceTest.java

Fix code so that it is not sensitive to presence/absence of trailing slash in the efs.mount property
Fix code so that it is not sensitive to presence/absence of trailing slash in the efs.mount property
N/A
N/A

AB2D 832 - Handle efs.mount path without trailing slash

---

api/pom.xml
api/src/main/java/gov/cms/ab2d/api/controller/BulkDataAccessAPI.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
common/src/main/java/gov/cms/ab2d/common/model/User.java
common/src/main/java/gov/cms/ab2d/common/service/JobService.java
common/src/main/java/gov/cms/ab2d/common/service/JobServiceImpl.java
common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v001/add_concurrent_job_column.sql
common/src/test/java/gov/cms/ab2d/common/service/JobServiceTest.java
common/src/test/java/gov/cms/ab2d/common/util/DataSetup.java
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java

Setting max concurrent jobs to 3
Add a column in the user_account table that will set the maximum concurrent jobs a user can have to 1 by default, and adding a migration that will change it to 3 for all users. The exports will enforce that a user can only have a max number of jobs to whatever their limit is set to.
NA

Setting max concurrent jobs to 3

---

worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessor.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorUnitTest.java

refactor async call to return void return type
After the design change to enable worker to create multiple output files, the logic no longer needs the errorCount to be returned by the `PatientClaimsProcessor` class. `JobProcessor` is able to use the `dataFiles` & `errorFiles` obtained from the `JobDataWriter` class to create the relevant records in the `JobOutput`  table. This refactor removes the redundant `errorCount` return type from being returned from the async call and the corresponding clean up of the code in `JobProcessor`
N/A
N/A

ab2d-931 - refactor async call to return void return type

---

api/src/main/resources/application.properties
docker-compose.yml
worker/src/main/resources/application.properties

Add a new parameter `sslmode` in the db connection URL to allow ssl connection to be turned on in specific environments
Add a new parameter `sslmode` in the db connection URL to allow ssl connection to be turned on in specific environments
Set the default value to `allow` which will **not** require ssl connection for dev and other non-prod environments. 
To turn on ssl in prod(and any other environments) , the value could be set to `verify-full` by setting the environment variable `AB2D_DB_SSL_MODE`

add new parameter to set sslmode to connect to db

---

bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientTest.java
bfd/src/test/resources/bb-test-data/eob/20010000001115.xml
bfd/src/test/resources/bb-test-data/eob/20140000008325.xml
bfd/src/test/resources/bb-test-data/eob/20140000008325_10.xml
bfd/src/test/resources/bb-test-data/eob/20140000008325_20.xml
bfd/src/test/resources/bb-test-data/eob/20140000008325_30.xml
bfd/src/test/resources/bb-test-data/eob/20140000009893.xml

While requesting EOB data from BFD, exclude substance abuse and mental health claims
While requesting EOB data from BFD, pass an additional search criteria to exclude substance abuse and mental health claims.
N/A
N/A

ab2d-974 - exclude SAMHSA while requesting EOB data from BFD

---

worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/domainmodel/ProgressTracker.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorUnitTest.java
worker/src/test/resources/application.properties

introduce failure threshold for the worker
Given a job, the worker processes all the patients in the contract. Introduce a failure threshold so that the batch is not stopped on the first failure. Instead when a failure occurs, check against an externally configurable failure threshold and if the number of errors crosses the threshold, only then stop processing the job.
N/A
N/A

ab2d 973 introduce failure threshold for the worker

---

common/src/main/java/gov/cms/ab2d/common/model/Contract.java
common/src/main/java/gov/cms/ab2d/common/repository/BeneficiaryRepository.java
common/src/main/java/gov/cms/ab2d/common/repository/CoverageRepository.java
worker/src/main/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterImpl.java
worker/src/main/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterStub.java
worker/src/main/java/gov/cms/ab2d/worker/service/BeneficiaryService.java
worker/src/main/java/gov/cms/ab2d/worker/service/BeneficiaryServiceImpl.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/BeneficiaryServiceIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/WorkerServiceTest.java
worker/src/test/resources/application.properties

Add ability to cache contract-to-bene data
Add the ability to worker to be able to cache the patientId and months active in a contract when the call the BDF contract-to-bene API returns a large amount of data. When processing a job, the `ContractAdapterImpl` will look at the cache first to see if we have the data, before attempting to call the remote api. A property named `contract2bene.caching.threshold` is used to configure this.
N/A
N/A

Feature ab2d 1070 Add ability to cache contract-to-bene data

---

e2e-test/src/test/java/gov/cms/ab2d/e2etest/APIClient.java
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
load-test/src/main/java/gov/cms/ab2d/loadtest/TestRunner.java
website/hidden/sandbox/windows-tutorial.md

Required an output type to be passed to the export endpoints where it could be ndjson or zip. The zip test makes sure a zip file is created and when downloaded, the contents look exactly like the contents of the ndjson.

Ab2d 1048 add zip download tests to e2e

---

api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIPropertiesTests.java
common/src/main/java/gov/cms/ab2d/common/service/PropertiesService.java
common/src/main/java/gov/cms/ab2d/common/service/PropertiesServiceImpl.java
common/src/main/java/gov/cms/ab2d/common/util/Constants.java
common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v001/add_contract2beneCache_toggle_property.sql
common/src/test/java/gov/cms/ab2d/common/service/PropertiesServiceTest.java
worker/src/main/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterImpl.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterTest.java
worker/src/test/resources/application.properties

ab2d 1105 add contract2bene  cache toggle switch
Add contract2bene cache toggle switch to turn caching on or off. 
It looks for a toggle named `ContractToBeneCachingOn` in the properties table with the value `true`
N/A
N/A

ab2d 1105 add contract2bene cache toggle switch

---

worker/src/main/java/gov/cms/ab2d/worker/processor/ContractProcessor.java
worker/src/main/java/gov/cms/ab2d/worker/processor/ContractProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractAdapterStubTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/ContractProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorUnitTest.java

refactor JobProcessor - extract ContractProcessor
Code-climate recommendation is to refactor JobProcessorImpl to simplify it.
JobProcessor has accumulated lot of logic and become large and complicated over time.  
Extracting ContractProcessor that encapsulates all the logic related to processing a contract, thereby simplifying JobProcessorImpl and help make the class smaller
N/A
N/A

AB2D 1190 refactor JobProcessor - extract ContractProcessor

---

.github/workflows/gitleaks_github_actions.yml

This PR Removes a newline character that was breaking links in security alerts.
When originally developing the gitleaks automation a manual newline character was inserted to separate the links of an alert. This no longer has any effect on the formatting in the alerts and just breaks the first link. This PR removes the unnecessary character to fix the link.
This impacts security alerting in a minor way by improving the alerting syntax to allow links to be easier to follow
Primary ticket not applicable, this is conducted as minor side effort in relation to AB2D-1304

Remove newline character that was breaking links in alerts

---

docker-compose.yml
eventlogger/src/main/java/gov/cms/ab2d/eventlogger/eventloggers/kinesis/KinesisEventLogger.java
eventlogger/src/main/java/gov/cms/ab2d/eventlogger/eventloggers/kinesis/KinesisEventProcessor.java
eventlogger/src/main/java/gov/cms/ab2d/eventlogger/eventloggers/sql/SqlEventLogger.java
eventlogger/src/main/resources/application.properties
eventlogger/src/test/java/gov/cms/ab2d/eventlogger/eventloggers/kinesis/KinesisEventLoggerTest.java

This PR contains both variables to turn off sending requests to Kinesis fire hoses in build environments or anywhere the environment isn't "local", the default. You have to explicitly change the environment variable AB2D_EXECUTION_ENV to have it log.
I also made some changes related to sending the data so it met some of the standards to the data source table/column names on AWS from camelcase to underscores. For example jobId = job_id, ErrorEvent = error_event

Ab2d 1488 turn off logging for build env

---

api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIPropertiesTests.java
api/src/test/java/gov/cms/ab2d/api/controller/MaintenanceModeAPITests.java
filter/src/test/java/gov/cms/ab2d/filter/EOBLoadUtilitiesTest.java
filter/src/test/java/gov/cms/ab2d/filter/EOBToAB2DEOBTest.java
filter/src/test/resources/eobdata/EOB-for-Carrier-Claims.json
filter/src/test/resources/eobdata/EOB-for-DME-Claims.json
filter/src/test/resources/eobdata/EOB-for-HHA-Claims.json
filter/src/test/resources/eobdata/EOB-for-Hospice-Claims.json
filter/src/test/resources/eobdata/EOB-for-Inpatient-Claims.json
filter/src/test/resources/eobdata/EOB-for-Outpatient-Claims.json
filter/src/test/resources/eobdata/EOB-for-Part-D-Claims.json
filter/src/test/resources/eobdata/EOB-for-SNF-Claims.json
website/assets/downloads/sample-data.ndjson
worker/src/main/java/gov/cms/ab2d/worker/processor/ContractProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessor.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/ContractProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobPreProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorUnitTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/stub/PatientClaimsProcessorStub.java
worker/src/test/resources/test-data/EOB-for-Carrier-Claims.json

If the patients not found in the contract beneficiary map, they should be excluded from the file.
Cleaned up the sample test data so they all referred to the same patient ID because some tests were using one patient ID but returning an EOB file with a different patient so based on this update, it would have been excluded.
This increases security by double checking results from BFD making sure the EOB records are only from patients who were included in the list of the contract's beneficiaries

Make sure patients not belonging to contracts are not included in files

---

common/src/main/resources/application.common.properties
common/src/test/resources/application.common.properties
docker-compose.yml
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
hpms/src/main/java/gov/cms/ab2d/hpms/hmsapi/HPMSAuthResponse.java
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthService.java
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSFetcherImpl.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
hpms/src/test/resources/application.hpms.properties

[AB2D-1969](https://jira.cms.gov/browse/AB2D-1969) - Add Authentication Headers on the HPMS call
None
This PR authenticates with HPMS and retrieves an authorization token for use in future HPMS API calls.
The token is cached for subsequent calls.
None
None
None
Dependent upon HPMS to issue more permanent credentials.  The current credential is limited to the IMPL environment for the month of September 2020.
- [x ] This PR includes any required documentation changes, (`README`, changelog / release notes, website).
- [ x] All tech debt and/or shortcomings introduced by this PR are detailed in `TODO` and/or `FIXME` comments.

Add Authentication Headers on the HPMS call

---

Deploy/bash/functions/fn_get_temporary_aws_credentials_via_cloudtamer_api.sh

[AB2D-1519](https://jira.cms.gov/browse/AB2D-1519) - Fix CloudTamer scripts to use different API endpoints
N/A
- updates the shared CloudTamer function from v2/token (developer only) to the recently released production v3/token
N/A
1. Change to the "ab2d" repo directory
1. Test "connect-to-node.sh" which used the changed function by entering the following
```ShellSession
$ ./Deploy/bash/connect-to-node.sh
```
N/A
N/A
N/A

change from developer v2 level token to prod v3 token

---

.travis.yml
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
worker/src/main/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractBeneSearchImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientContractCallable.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/ContractBeneSearchTest.java
worker/src/test/java/gov/cms/ab2d/worker/adapter/bluebutton/LoadPatientsByContractLoggingTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/BundleUtils.java
worker/src/test/java/gov/cms/ab2d/worker/processor/MultiThreadContractProcessTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/MultiThreadContractSearchIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientContractCallableLiveTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientContractCallableTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/ProgressTrackerIntegrationTest.java
worker/src/test/resources/application.properties

[AB2D-2325](https://jira.cms.gov/browse/AB2D-2325) - Filtering Coverage By Year
Changes to prevent leaking PHI by filtering for accurate coverage periods. These changes enforce date filtering when finding coverage mapping information by forcing the specific year.
1. PatientContractCallable now filters by a provided year.
2. Year is set via an environment variable PATIENT_CONTRACT_YEAR.
3. PatientContractCallable now logs discarded patients by provided year and those missing an identifier
4. Clean up tests by removing duplicate methods in BundleUtils

patient contract callable modified to filter by year

---

common/src/main/java/gov/cms/ab2d/common/model/TimestampBase.java
common/src/test/java/gov/cms/ab2d/common/model/CreateUpdateTimestampTest.java

Change to OffsetDateTime so timezone is tracked in database.
[AB2D-2257](https://jira.cms.gov/browse/AB2D-2257) - LocalDateTime Used for Created and Modified Model
Just change a couple datatypes

TimestampBase use OffsetDateTime

---

Jenkinsfile
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSFetcherTest.java

[AB2D-2481](https://jira.cms.gov/browse/AB2D-2481) - Clear out auth cache.
Fixes a bug in testing discovered when converting to Jenkins as the test execution order differred.

When testing, clear out the cached auth token.

---

bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/PatientContractCallable.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientContractCallableLiveTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientContractCallableTest.java

[AB2D-2568](https://jira.cms.gov/browse/AB2D-2568) - Passthrough Missing MBIs
[AB2D-2530](https://jira.cms.gov/browse/AB2D-2530) - Original MBI handling
Allow beneficiaries without an mbi to still be queried for EOBs instead of pre-emptively filtering. Additionally, add include identifiers onto every bundle request for contract membership information.
* Make sure that null MBIs won't cause NPEs

passthrough missing mbis

---

bfd/src/main/java/gov/cms/ab2d/bfd/client/BFDClientImpl.java
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java

[AB2D-2606](https://jira.cms.gov/browse/AB2D-2606) - Description
Disable portion of contract membership search corresponding to MBIs. Null values are passed through system and ignored for the moment.
All disabled areas are marked with todos to re-enable once this issue has been resolved.
Any potential issues writing out eobs to file with null mbis. Any potential issues with MBIs being null that might cause an NPE.

Disable MBI Searches Temporarily

---

api/src/test/resources/application.properties
audit/src/test/resources/application.audit.properties
worker/src/test/resources/application.properties

[AB2D-2734](https://jira.cms.gov/browse/AB2D-2734) - Quartz Hostname Error Jenkins CI
Add a bug fix to fix hostname resolution bug with quartz in CI. This issue does not present itself in the production environments which run inside containers.
The potential that this issue extends to containers as well as VMs.

set quartz instance id to try to deal with hostname issues

---

audit/src/test/java/gov/cms/ab2d/audit/cleanup/FileDeletionServiceTest.java
common/src/main/resources/application.common.properties
common/src/test/resources/application.common.properties
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
website/advanced-user-guide.md
worker/src/main/resources/application.properties

[AB2D-2725](https://jira.cms.gov/browse/AB2D-2725) - Description
Changes the expiration date for files from 24 to 72 hours in the code and in documentation.
Changed it in the ab2d-private- production documentation

Changed default file deletion from 24 hours to 72 for slow or large PDPs

---

api/src/test/java/gov/cms/ab2d/api/security/JwtAuthenticationFilterTest.java

[AB2D-42](https://jira.cms.gov/browse/AB2D-2856) - Delete Jobs before users
Works around issues with the setUp() method hitting a FK constraint.

Delete order fix to try to get master happy again.

---

api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIMaintenanceModeTests.java
api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIPropertiesTests.java
api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIUserTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIUnusualDataTests.java
api/src/test/java/gov/cms/ab2d/api/controller/InvalidTokenTest.java
api/src/test/java/gov/cms/ab2d/api/controller/TLSTest.java
api/src/test/java/gov/cms/ab2d/api/controller/TestUtil.java
bfd/src/test/java/gov/cms/ab2d/bfd/client/BFDClientConfigurationTest.java
bfd/src/test/java/gov/cms/ab2d/bfd/client/BlueButtonClientTest.java
common/src/test/java/gov/cms/ab2d/common/model/CoverageSearchTest.java
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
eventlogger/src/main/java/gov/cms/ab2d/eventlogger/utils/UtilMethods.java
eventlogger/src/test/java/gov/cms/ab2d/eventlogger/LogManagerTest.java
eventlogger/src/test/java/gov/cms/ab2d/eventlogger/eventloggers/sql/AllMapperEventTest.java
filter/src/test/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerTest.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/AttestationUpdaterServiceTest.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceTest.java
hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSFetcherTest.java
worker/src/test/java/gov/cms/ab2d/worker/bfdhealthcheck/BFDHealthCheckTest.java
worker/src/test/java/gov/cms/ab2d/worker/properties/PropertiesChangeDetectionTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/FileServiceIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/stuckjob/CancelStuckJobsProcessorTest.java

[AB2D-2954](https://jira.cms.gov/browse/AB2D-2954) - Remove JUnit4 
Update unit tests to use JUnit5 only and fix incorrect argument orderings which cause misleading failure messages.
Accidental modification of the semantics of a test.

remove junit and change ordering of arguments to assertions

---

Deploy/bash/deploy-application.sh
Deploy/bash/deploy-worker-module.sh
Deploy/bash/update-gold-disk.sh
Deploy/packer/app/app.json
Deploy/packer/app/provision-app-instance.sh
Deploy/terraform/environments/ab2d-dev/main.tf
Deploy/terraform/environments/ab2d-dev/variables.tf
Deploy/terraform/environments/ab2d-east-impl/main.tf
Deploy/terraform/environments/ab2d-east-impl/variables.tf
Deploy/terraform/environments/ab2d-east-prod-test/worker/input.tf
Deploy/terraform/environments/ab2d-east-prod-test/worker/worker.tf
Deploy/terraform/environments/ab2d-east-prod/main.tf
Deploy/terraform/environments/ab2d-east-prod/variables.tf
Deploy/terraform/environments/ab2d-sbx-sandbox/main.tf
Deploy/terraform/environments/ab2d-sbx-sandbox/variables.tf
Deploy/terraform/modules/api/main.tf
Deploy/terraform/modules/api/userdata.tpl
Deploy/terraform/modules/api/variables.tf
Deploy/terraform/modules/terraservices_pattern/worker/input.tf
Deploy/terraform/modules/terraservices_pattern/worker/userdata.tpl
Deploy/terraform/modules/terraservices_pattern/worker/worker.tf
Deploy/terraform/modules/worker/main.tf
Deploy/terraform/modules/worker/userdata.tpl
Deploy/terraform/modules/worker/variables.tf

[AB2D-2941](https://jira.cms.gov/browse/AB2D-2941) - Fix EFS mounts Not Using TLS
This PR Fixes an issue with running Stunnel in FIPS mode, therefore allowing TLS connection to EFS Mounts in AWS. Specifically, this PR removes Stunnel configuration from Terraform and moves it into Packer.
Semantically this means that instead of configuring the TLS connection to EFS after creating a VM we are baking it into the VM image.
The new Packer config that saves time on deployments (approx 11 mins) 
Standard Deployment (already deployed in all envs)
EFS Mounts (Now over TLS)
N/A
Must be run on a FIPS Compliant kernel or Gold AMI
N/A - Devops Changes

Bug/ab2d 2941 Fix EFS Not Using TLS

---

worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverUnitTest.java

[AB2D-2957](https://jira.cms.gov/browse/AB2D-2957) - Since Parameter Applied Incorrectly to Enrollment Data
Fix bug introduced in CoverageDriver that was incorrectly applying the since parameter to enrollment data. The since parameter is only meant for usage with claims data. The since parameter filters by the time a claim was received/updated in BFD and not by the time that services were rendered.
Any other usages of since that may have snuck into the CoverageProcessor or other coverage classes.

remove usage of since for enrollment calculation

---

api/src/main/java/gov/cms/ab2d/api/security/SecurityConfig.java
api/src/test/java/gov/cms/ab2d/api/controller/RoleTests.java

[AB2D-3033](https://jira.cms.gov/browse/AB2D-3033) - Limit ADMIN role access to the api
Disallow the ADMIN user downloading data from any FHIR endpoints in our api. If we are going to give the ADMIN user the ability to start any job, for security, we should prevent the ADMIN user from being able to download the results of that job.

limit ADMIN role access to FHIR resources

---

e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
filter/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR3.java
filter/src/main/java/gov/cms/ab2d/filter/ExplanationOfBenefitTrimmerR4.java

[AB2D-2963](https://jira.cms.gov/browse/AB2D-2963) - Report EOB.status on Claims
Stops filtering the `eob.status` field. This field is the only field that a PDP can use to detect whether a claim is the latest version ('active') is a stale version ('cancelled') or has been altogether cancelled ('cancelled').
Wait for comment with approval from CMS.

remove filter for eob.status field

---

api/src/main/java/gov/cms/ab2d/api/controller/AdminAPI.java
api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIUserTests.java
common/src/main/java/gov/cms/ab2d/common/repository/UserRepository.java
common/src/main/java/gov/cms/ab2d/common/service/UserService.java
common/src/main/java/gov/cms/ab2d/common/service/UserServiceImpl.java
common/src/test/java/gov/cms/ab2d/common/service/UserServiceTest.java

[AB2D-3032](https://jira.cms.gov/browse/AB2D-3032) - Admin API Endpoints
Change the Admin endpoints to stop using okta client ids and start using only contract numbers for starting jobs.

change admin api to start jobs by contract number not username

---

common/src/main/java/gov/cms/ab2d/common/service/CoverageServiceImpl.java

[AB2D-2976](https://jira.cms.gov/browse/AB2D-2976) - Description
Computes delta only if the previous search had actual data.

Bug fix, only compute delta when a previous search has elements.

---

common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v2021/remove_extra_users.sql

[AB2D-2508](https://jira.cms.gov/browse/AB2D-2508) - Remove non-okta user accounts
Removes all users that are disabled. These users (in production and in sandbox) are not okta credentials. Any okta credential in the user_account table is currently enabled.
Removes all non-okta users manually created by liquibase for testing.
See add_multicontract_data.sql, all user accounts not beginning with a zero are not okta users.
Remove multi-contract okta users being tested in sandbox
Any user_accounts that might inadvertently be deleted by the queries.
These queries have been tested as select statements in production.

add sql to remove all disabled users and manually added nonokta users

---

api/src/main/java/gov/cms/ab2d/api/controller/AdminAPI.java
api/src/main/java/gov/cms/ab2d/api/controller/ErrorHandler.java
api/src/main/java/gov/cms/ab2d/api/controller/HealthAPI.java
api/src/main/java/gov/cms/ab2d/api/controller/common/ApiCommon.java
api/src/main/java/gov/cms/ab2d/api/controller/common/FileDownloadCommon.java
api/src/main/java/gov/cms/ab2d/api/controller/common/StatusCommon.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/CapabilityAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v2/CapabilityAPIV2.java
api/src/main/java/gov/cms/ab2d/api/security/JwtTokenAuthenticationFilter.java
api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIPdpClientTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
common/src/main/java/gov/cms/ab2d/common/util/Constants.java
common/src/test/java/gov/cms/ab2d/common/util/DataSetup.java

[AB2D-3407](https://jira.cms.gov/browse/AB2D-3407) - API Event Organization Missing
The JwtAuthenticationFilter was logging client ids. Change switches from logging client ids to logging the organization name which is not a sensitive piece of information.
All of the API response events also were attempting to log okta client ids. This has been updated to use the organization instead of the client id.
Fortunately, the SQL and Kinesis loggers were filtering those out but the rows are null in the dev environment.
Any way the authentication filter could behave differently now than before this change.

bug/ab2d-3407 ApiRequestEvent Organization Missing

---

api/src/main/java/gov/cms/ab2d/api/controller/v1/CapabilityStatementSTU3.java

[AB2D-42](https://jira.cms.gov/browse/AB2D-3493) - Reduced precision for date
The date in the STU3 capability statement is so precise that tests are failing because the generated capability statement is one second off the received version. Remove the seconds precision. Still may have issue across minutes but a lot less likely.

Reduced precision for date

---

api/src/main/java/gov/cms/ab2d/api/security/JwtTokenAuthenticationFilter.java
api/src/main/java/gov/cms/ab2d/api/security/SecurityConfig.java
api/src/main/resources/application.properties
api/src/test/java/gov/cms/ab2d/api/security/JwtAuthenticationFilterTest.java
common/src/main/java/gov/cms/ab2d/common/util/Constants.java
common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v2021/delete_akamai_requests.sql

[AB2D-3621](https://jira.cms.gov/browse/AB2D-3621) - Akamai Test Object
* Delete existing records for GET `/akamai-test-object.html` in our response and request tables
* Prevent logging future `/akamai-test-object.html` GET requests in our database
* Mark routine calls as debug logging instead of info logging
* Allow GET requests `/akamai-test-object.html` without a bearer token
If we don't allow akamai calls without a bearer token we will continue receiving errors for 401 unauthorized every time the call is made regardless of whether logging for the akamai calls are enabled or disabled.
Any significant change to the security posture of the api that may result from this.

filter akamai health checks

---

api/Dockerfile
worker/Dockerfile

Change from OpenJ9 which limits the JVM to 25 GB of RAM. New JVM will be Hotspot maintained by Oracle.

Switch to Hotspot JVM

---

common/src/main/java/gov/cms/ab2d/common/service/CoverageService.java
common/src/main/java/gov/cms/ab2d/common/service/CoverageServiceImpl.java
common/src/test/java/gov/cms/ab2d/common/service/CoverageServiceImplTest.java
worker/src/main/java/gov/cms/ab2d/worker/config/JobHandler.java
worker/src/main/java/gov/cms/ab2d/worker/processor/JobPreProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageProcessorImpl.java
worker/src/main/java/gov/cms/ab2d/worker/service/WorkerServiceImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobPreProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageUpdateAndProcessorTest.java

[AB2D-3441](https://jira.cms.gov/browse/AB2D-3441) - Fail Job if Enrollment Loading Fails
Force the failure of an EOB job if the underlying enrollment information cannot be pulled. This PR changes the process for retrying an enrollment search to avoid marking a job as failed until after max retries is exceeded.
Cases where the `CoverageDriverException` is not thrown but coverage retries may be exceeded.

Fail Job if Enrollment Loading Fails

---

Jenkinsfile
e2e-patient-test/src/test/java/gov/cms/ab2d/patientendpoint/PatientEndpointTests.java
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
e2e-test/src/test/resources/logback.xml
pom.xml
worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageMappingCallable.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageMappingCallableTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageUpdateAndProcessorTest.java

[AB2D-3766](https://jira.cms.gov/browse/AB2D-3766) - Fix tests
The new BFD Patient endpoint defaults to the current year instead of no year if no year is provided. This causes test to fail since all attribution data for sandbox data is in the year 3. The year 3 has to be explicitly passed during sandbox e2e tests

Update tests & code to handle new BFD Patient endpoint

---

worker/src/main/java/gov/cms/ab2d/worker/config/CoverageQueueConfig.java
worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageProcessorImpl.java
worker/src/main/resources/application.properties
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageUpdateAndProcessorTest.java
worker/src/test/resources/application.properties

[AB2D-3815](https://jira.cms.gov/browse/AB2D-3815) - Enrollment Thread Pool Size
ThreadPoolTaskExecutors uses queue capacity to dictate when to increase the number of threads in the pool. This is too complicated for enrollment and frankly we don't care about scaling this pool. So instead the pool size is going to be hard-coded to the same core pool size and max pool size. Logic is in place to prevent adding jobs when the pool is full.

remove max pool size param and set core pool to fixed value

---

website/accessing-claims-data.md

[AB2D-3763](https://jira.cms.gov/browse/AB2D-3763):
The text on the bottom of this page needs to be black instead of green. https://ab2d.cms.gov/accessing-claims-data.html
The text reads:
For more information and to help answer any remaining question you may have, production documentation can be found in the AB2D Githhub repository."
That linked text is OK to stay linked. The rest needs to be black instead of green
Updates the last point on Accessing Claims Data page to be black instead of green
Ensure the text is black
N/A

AB2D-3763 Update text from green to black

---

hpms/src/test/java/gov/cms/ab2d/hpms/service/HPMSFetcherTest.java
worker/src/main/java/gov/cms/ab2d/worker/processor/ContractProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/ContractProcessorUnitTest.java

[AB2D-3901](https://jira.cms.gov/browse/AB2D-3901) - Skipping Patients When Queue Full
Patients are being skipped when the queue is full. This PR fixes the issue and provides a unit test for detecting regressions in the future.
* Switch from for back to while loop
* Create unit test for verifying fix

Skipping patients during jobs

---

fhir/src/main/java/gov/cms/ab2d/fhir/IdentifierUtils.java
fhir/src/test/java/gov/cms/ab2d/fhir/PatientIdentifierUtilsTest.java
fhir/src/test/resources/data/r4patients.json

[AB2D-3894](https://jira.cms.gov/browse/AB2D-3894) - Not picking up currency of R4 MBIs in Patient Identifiers
While doing some Synthea testing, I noticed that we were not finding the currency (current or historic) values for the MBIs, even when they were present. It was marking them as UNKNOWN.
Under further investigation, it looks like BFD reverted to the MBI identifier system URL they used for STU3 instead of the new one they said they were going to use for R4. The currency was still in the new place for R4 but because the system of the identifier was the old STU3 version, it was never finding the value because because it was only looking in the STU3 location.
Also did some variable cleanup and updated the patient R4 json test file with the most current implementation …

Wasn't finding the currency on R4 MBI Identifiers

---

worker/src/main/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/PatientClaimsProcessorUnitTest.java

[AB2D-4004](https://jira.cms.gov/browse/AB2D-4004) - Since Date not Verified for EOB Requests
Fix a bug where it was possible to give a bad since date as part of an EOB request. Providing a bad since date would either lead to slow performance or it being ignored.
Other checks prevent providing data before the ab2d epoch or a contract's attestation date so this would not lead to providing extra data.

Verify since date before making eob request

---

pom.xml

Springboot dependencies has been updated to include up-to-date versions of log4j and logback that are not vulnerable to the disclosed CVEs.
We no longer need to pin the versions of log4j and logback in our parent pom.

Remove Pinned Log4J and Logback Versions given Springboot Updates

---

hpms/src/main/java/gov/cms/ab2d/hpms/config/WebClientConfig.java
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSAuthServiceImpl.java
hpms/src/main/java/gov/cms/ab2d/hpms/service/HPMSFetcherImpl.java

[AB2D-42](https://jira.cms.gov/browse/AB2D-4238) - Eliminate HPMS Connection Errors
It configures a single WebClient that does not use the default connection pool.  In fact, it uses no connection pool.  Given the reactive model coupled with running only once an hour, there really is no benefit to using a connection pool.  The drawbacks are stale connections in the default pool that generate these errors.

HPMS Connection Reset Errors

---

api/src/main/java/gov/cms/ab2d/api/controller/common/FileDownloadCommon.java

[AB2D-4332](https://jira.cms.gov/browse/AB2D-4332) - The new swagger errors out when you try to download the files
Updates response header to give swagger instructions. It prevents it from hanging and allows users to download the file with a click
There should be no impact for other clients
Deploy to sandbox

Updated header for file so that it doesn't error out with swagger

---

hpms/src/main/java/gov/cms/ab2d/hpms/service/AttestationUpdaterServiceImpl.java

[AB2D-4363](https://jira.cms.gov/browse/AB2D-4363) - Fixes the case where a contract has both an informational change and an attestation change. A stale object was then used.
Bug fix for Update issue for E4744.

Fixes stale contract usage.

---

api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/remote/JobClientMock.java

Fixed brittleness in BulkDataAccessAPIIntegrationTests by allowing the checks for Expires headers to not be an exact match but to allow for a window of test delay (7 seconds).
[AB2D-4458](https://jira.cms.gov/browse/AB2D-4458) - Fix brittleness in BulkDataAccessAPIIntegrationTests
Converts a timestamp exactness check to allow for a window of time so that the build will consistently pass.  As it was, sometimes the test running on jenkins would straddle a second boundary causing the test to fail.

AB2D-4458: Fix brittleness in BulkDataAccessAPIIntegrationTests

---

api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
job/src/test/java/gov/cms/ab2d/job/service/JobServiceTest.java
job/src/test/java/gov/cms/ab2d/job/service/MaxJobsTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/ShutdownServiceTest.java

[AB2D-4449](https://jira.cms.gov/browse/AB2D-4449) - Add job max tests previously dropped.
Given the separation of JobService into it's own module and the fact that the api module now works through a job client, there were a couple of tests that were no longer appropriate in the api module.  Due to the massive size of an earlier refactoring they were moved into a JIRA ticket to be re-added later when the JobService was moved into its own module.
This PR restores the tests but in a more narrow focus specifically testing JobService features, not the overall MockMVC calls.
Also, noticed that build #141 on master failed which turned out to be a timing issue with comparing timestamps.  Created a custom matcher that can tolerate the test running across a …

Add dropped max job tets

---

worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
worker/src/main/java/gov/cms/ab2d/worker/quartz/CoveragePeriodQuartzJob.java
worker/src/test/java/gov/cms/ab2d/worker/quartz/CoveragePeriodQuartzJobTest.java

[AB2D-4745](https://jira.cms.gov/browse/AB2D-4745) - Diagnose issue with coverage data not updating
Fix the issue with stale coverage data not being searched.
On 6/1/2022 we received an alert saying that coverage data was out of date. The incident is covered [here](https://confluence.cms.gov/display/AB2D/2022-06-01+AB2D+Missing+Enrollment+Data).
After some investigation (and adding debug statements), it appears that the application is running out of time to add stale data to the search queue. Originally, it was only allowed 1 hour to add items to the queue. Because it has a maximum queue size before it considered it "full", and the queue has to open up some space before another item is added, many period searches weren't being added to the search queue before that hour …

Fixed issue with stale coverage periods not able to add to search queue

---

worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/check/CoveragePresentCheck.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/check/CoverageCheckPredicatesDisableAlertTest.java

[AB2D-AB2D-5089](https://jira.cms.gov/browse/AB2D-5089) - Description
Disable coverage alert for S3147-2021-12.
Adds a new method that tests if the current coverage check is for S3147-2021-12. If it is, don't send an alert. 
Possible regressions.

ignored coverage check for S3147-2021-12

---

worker/src/main/resources/application.properties

https://jira.cms.gov/browse/AB2D-5436
Revert logging level from DEBUG to INFO level
After the PR1202 merge, the environments experienced logging errors with the DEBUG level.
We want errors to be only with INFO level

Change logging level

---

e2e-test/src/test/resources/logback.xml

https://jira.cms.gov/browse/AB2D-5704
Revert logging level from DEBUG to INFO level in e2e tests
After the PR1202 merge, the environments experienced logging errors with the DEBUG level.
We want errors to be only with INFO level

Update logging lever for e2e tests

---

common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v2023/add_columns_to_coverage.sql
common/src/main/resources/db/changelog/v2023/add_optout_property.sql

https://jira.cms.gov/browse/AB2D-5622
Added new columns opt_out boolean field and effective date timestamp field.
Add new row OptOutOn to property table
Changed the "changelog-master.yaml" to include newly includedSQL files for opt out.
Opt-out :
STEP 1: On a weekly basis AB2D makes calls to BFD to retrieve contract bene mappings and store on AB2D database.. this end point already exists on BFD. That flat file will be written to BFD s3..
Step 2: Ab2d need to read that flat file with opted out bene data from BFD s3 update in AB2d database.
This PR addresses part 2 to create the fields necessary in DB to store the ingested data from s3.
Tested locally
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) as a reviewer and do not merge this PR without his …

AB2D-5622 update database

---

common/src/main/java/gov/cms/ab2d/common/util/PropertyConstants.java
common/src/test/java/gov/cms/ab2d/common/properties/PropertyServiceStub.java
coverage/src/main/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepository.java
coverage/src/test/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepositoryTest.java

the database, there is logic to use the new columns and fields to programmatically filter out beneficiaries from the AB2D response
https://jira.cms.gov/browse/AB2D-5622
Created Select and Count of beneficiaries statements to use values from opt_opt_flag column in public.coverage table.
Added ability to use statements with or without opt_out_flag based on OptOutOn property
Step 2 for Opt-Out feature

AB2D-5622 OptOut Filtering

---

api/src/main/java/gov/cms/ab2d/api/controller/v1/BulkDataAccessAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/CapabilityAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/FileDownloadAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/StatusAPIV1.java

https://jira.cms.gov/browse/AB2D-5637
Added number in Tags for endpoints to adjust the alphabetical order.
I found that sorting endpoints in Swagger is not trivial task. We currently use alphabetical order:
```
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha  
```
The numbers before the text in the endpoint tags will help us to change the order in the Swagger UI.
Deployed on IMPL:

AB2D-5637 Enhance sandbox documentation based on connectathon feedback

---

common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v2023/create_current_mbi_procedure.sql
common/src/main/resources/db/changelog/v2023/create_current_mbi_table.sql
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/check/CoverageCheckPredicatesIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/check/CoverageCheckPredicatesUnitTest.java

https://jira.cms.gov/browse/AB2D-5782
- Added `create_current_mbi_table.sql` liquibase file where I create a new table `public.current_mbi` and insert unique current mbis from `public.coverage table`.
- Added `create_current_mbi_procedure.sql` liquibase file where I create a procedure to insert values from 2023 partition to  `public.current_mbi` table 
Performance of the AttributionDataShare Lambda in production will need some kind of persistence. An easy way to do this based on our existing architecture that the engineering team has discussed is by utilizing a database procedure. 
Deployed the branch on dev:

AB2D-5782 Database changes for AttributionDataShare Lambda

---

common/src/main/resources/db/changelog/db.changelog-master.yaml
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageCheckIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/check/CoverageCheckPredicatesIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/check/CoverageCheckPredicatesUnitTest.java

https://jira.cms.gov/browse/AB2D-xxx
Some tests fail in several month and the previouse team hardcoded May in tests since we currently don't have any special logic for that month.
However, hardcoding for May wasn't applied.
Unit tests pass

Ab2 d/fix integration tests for may

---

.github/workflows/unit-integration-test.yml

https://jira.cms.gov/browse/PLT-278
Switch to the new deploy role for AB2D dev.
Work in PLT-278 changed the roles for deploy across accounts.
See checks.
None.

PLT-278 Switch to new deploy role

---

api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIMaintenanceModeTests.java
api/src/test/java/gov/cms/ab2d/api/controller/TLSTest.java
common/pom.xml
common/src/test/java/gov/cms/ab2d/common/util/AB2DSQSMockConfig.java
pom.xml

https://jira.cms.gov/browse/AB2D-5916
WIP - Still might need some cleanup
Remove dependency on org.springframework.cloud
Update Spring AWS Cloud dependency from 2.2.6 to 2.4.4 by migrating to io.awspring.cloud.
Update AB2D Libs versions
This is required to potentially use IMDSV2 to fix EC2 issues.
Built locally, to be deployed and tested on IMPL environment

[AB2D-5916] AWS Cloud Dependency Upgrade

---

common/src/main/resources/db/changelog/v2024/misc_opt_out_attribution.sql

https://jira.cms.gov/browse/AB2D-6039
Changed effective_date column type from Timestamp to Date
Fix for the exception:
```
gov.cms.ab2d.attributionDataShare.AttributionDataShareException: An error occurred while exporting data to a file. 
at gov.cms.ab2d.attributionDataShare.AttributionDataShareHelper.copyDataToFile(AttributionDataShareHelper.java:53)
at gov.cms.ab2d.attributionDataShare.AttributionDataShareHandler.handleRequest(AttributionDataShareHandler.java:41)
Caused by: org.postgresql.util.PSQLException: Bad value for type timestamp/date/time: t
```
Tested on impl

AB2D-6039/Columnt_type_change

---

common/src/main/resources/db/changelog/v2024/misc_opt_out_attribution.sql

https://jira.cms.gov/browse/AB2D-6051
Changed the stored procedure to pull data from contracts and populate current_mbi table
As part of the automated enrollee opt-out workflow, AB2D sends a weekly (Tuesday at night) request file that has beneficiaries aligned with AB2D. Currently the request file only includes PDPs that have run a production job (who we have shared beneficiary information with). We want to expand the list by including all PDPs that have attested, currently or in the past.
The request file includes beneficiaries that belong to PDPs who have attested, currently or in the past
There is no negative performance impact

6051- include all PDP's as part of attribution data share

---

Jenkinsfile
docker-compose.jenkins.yml
docker-compose.yml

https://jira.cms.gov/browse/PLT-467
Downgraded docker compose and disabled e2e test.
Docker compose upgrade was reverted because newer versions of docker compose require changes to our configuration files and dependencies. The e2e test was disabled because it is outdated and we have the same coverage with integration tests, e2e-bfd, and smoke tests in the transition to GitHub Actions.
See builds at https://jenkins.ab2d.cms.gov/job/AB2D%20Repo/view/change-requests/job/PR-1332/.
None.

PLT-467 downgrading docker compose & removing e2e test

---

common/src/main/java/gov/cms/ab2d/common/model/Role.java

https://jira.cms.gov/browse/AB2D-6099
HashSet implements serializable already, which makes me believe that the issue here is that the Role Entity itself needs to be serializable, as anything you put in a set needs to be in order for the HashSet to be serializable. 
This PR makes Role Serializable, which may resolve the following code smell:
This is part of the work done for 6099, but it is to catch a 'critical' code smell that was missed.
This will need to be deployed to master in order to get an accurate representation of code smells on AB2D. We will also need to test all code smell resolutions in a lower environment in a followup ticket to ensure functionality and performance remains the same or better.
If any security implications apply, add Jason Ashbaugh (GitHub username: StewGoin) …

[AB2D-6099] Make Role Serializable

---

worker/src/main/java/gov/cms/ab2d/worker/processor/ContractProcessorImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/ContractProcessorUnitTest.java

https://jira.cms.gov/browse/AB2D-6157
Added threshold for the alert
Currently slack shows jobs have failed due to a mismatch in data that is cause by the Null MBI issue. 
We'd like to update the slack alert to only show a failure if the mis matches reach a threshold higher that 10. Otherwise the job should show as a success as the job does complete for the PDP to receive the data.

AB2D-6157 Update mismatch job failure to pass in slack alerts

---

worker/src/main/java/gov/cms/ab2d/worker/processor/JobProcessorImpl.java

https://jira.cms.gov/browse/AB2D-6168
Disabled mismatch alert for S4802
Currently slack shows mismatch alert like 
EOB_JOB_CALL_FAILURE [d6620aa3-cc09-4cfd-bdaf-0fb10eb5cc2e] expected beneficiaries (8783362) does not match processed beneficiaries (9155611)ab2d-east-prod
EOB_JOB_QUEUE_MISMATCH [d6620aa3-cc09-4cfd-bdaf-0fb10eb5cc2e] expected beneficiaries (8783362) does not match queued beneficiaries (9155611)
We'd like do not see these types of slack alert for S4802 contract because of custom 1 month solution

AB2D-6168 Do not throw mismatch slack alerts for S4802

---

api/src/main/java/gov/cms/ab2d/api/controller/common/ApiText.java
api/src/main/java/gov/cms/ab2d/api/controller/common/FileDownloadCommon.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/BulkDataAccessAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/FileDownloadAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v1/StatusAPIV1.java
api/src/main/java/gov/cms/ab2d/api/controller/v2/BulkDataAccessAPIV2.java
api/src/main/java/gov/cms/ab2d/api/controller/v2/FileDownloadAPIV2.java
api/src/main/java/gov/cms/ab2d/api/controller/v2/StatusAPIV2.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
common/src/main/java/gov/cms/ab2d/common/util/Constants.java
job/src/test/java/gov/cms/ab2d/job/service/JobServiceTest.java
job/src/test/java/gov/cms/ab2d/job/service/MaxJobsTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobPreProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/processor/JobProcessorIntegrationTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/WorkerServiceDisengagementTest.java
worker/src/test/java/gov/cms/ab2d/worker/service/WorkerServiceTest.java

https://jira.cms.gov/browse/AB2D-6141
Rename constant from 'FIRE' to 'FHIR'
Update API Accept and Response values so that we are in-line with the FHIR specification:
https://build.fhir.org/ig/HL7/bulk-data/export.html#headers
This PR changes our accept headers on the export endpoint to accept both Application/fhir+json (the default expected by the FHIR standard: https://build.fhir.org/ig/HL7/bulk-data/export.html#headers, and Application/json, which is what is currently supported by our API.
Changes were deployed to IMPL environment and requests with different accept headers were made:
Application/json:
Application/fhir+json:

[AB2D-6141] Update API Accept Headers

---

coverage/src/main/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepository.java
coverage/src/test/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepositoryTest.java

https://jira.cms.gov/browse/AB2D-6187
Adds tests for `CoverageServiceRepository`. Modifies the source code very slightly in the name of getting test coverage on the `vacuumCoverage` method.

[AB2D-6187] increase `coverage` test coverage

---

api/src/main/java/gov/cms/ab2d/api/controller/common/ApiCommon.java
api/src/test/java/gov/cms/ab2d/api/controller/common/ApiCommonTest.java

https://jira.cms.gov/browse/AB2D-6187
Adds test coverage for `ApiCommon`

[AB2D-6187] increase `api` test coverage

---

worker/pom.xml

https://jira.cms.gov/browse/AB2D-6190
Ignore code coverage for `JobProcessorImpl`
`JobProcessorImpl` [has a custom fix for Centene that doesn't have code coverage](https://sonarqube.cloud.cms.gov/component_measures?id=ab2d-project&metric=new_lines_to_cover&branch=main&view=list&selected=ab2d-project%3Aworker%2Fsrc%2Fmain%2Fjava%2Fgov%2Fcms%2Fab2d%2Fworker%2Fprocessor%2FJobProcessorImpl.java), which is making the SonarQube quality gate fail. Because of this, CI has been failing in the `main` branch for quite some time. In order for CI to be passing again, we have to ignore this file in code coverage.

[AB2D-6190] Ignore Custom fix for Centene

---

common/src/main/resources/db/changelog/db.changelog-master.yaml
common/src/main/resources/db/changelog/v2024/ab2d_6151_rename_column.sql
coverage/src/main/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepository.java
coverage/src/test/java/gov/cms/ab2d/coverage/repository/CoverageServiceRepositoryTest.java

https://jira.cms.gov/browse/AB2D-6151
We should update the column name to data_sharing or share_data:
column name of opt_out is updated to share_data
no reduction in test coverage
1-800 opt out was rolled out on 4/6. The data sharing preference field in ICD can be true or false (or blank): When it is true, it means the beneficiary has chosen to share their data; when it is false, it means beneficiary has chosen to not share their data. The data sharing preference (specific in ICD) field is currently mapped to opt_out, which causes confusion as the column name contradicts the meaning of the field. column name of opt_out is updated to share_data
Verify to make sure that changes update the table column name .

Rename current mbi  opt out column name

---

.github/workflows/e2e-test.yml
.github/workflows/unit-integration-test.yml
e2e-test/src/test/java/gov/cms/ab2d/e2etest/TestRunner.java
e2e-test/src/test/resources/impl-config.yml

https://jira.cms.gov/browse/PLT-136
Added workflow for running e2e tests on the impl environment.
This e2e-test workflow should allow us to gain confidence in deploying while simplifying our test pipelines by running tests directly against resources in the impl environment.
We may need to merge this before we can test running the workflow.
None, these tests are run on self-hosted runners within our internal network.

PLT-136 Run e2e tests on impl environment

---

api/src/main/java/gov/cms/ab2d/api/security/FilterChainExceptionHandler.java
api/src/main/java/gov/cms/ab2d/api/security/JwtTokenAuthenticationFilter.java
api/src/main/java/gov/cms/ab2d/api/security/SecurityConfig.java

https://jira.cms.gov/browse/AB2D-6303
Reordered antMatchers in SecurityConfig so that authExceptions come first.
Expanded the authExceptions for metadata from "/metadata" to "**/metadata" so that it works with v1 and v2. Added a /metadata clause to shouldBePublic.
In order to conform with the Bulk Data IG (and pretty much any server IG) it should be possible to get a CapabilityStatement from the /metadata endpoint without having a bearer token.
Deployed branch to IMPL and checked to see that you can get a CapabilityStatement from the /metadata endpoint for both v1 and v2 by using Postman.

AB2D-6303 Get CapabilityStatement without bearer token

---

.github/workflows/unit-integration-test.yml
api/src/main/java/gov/cms/ab2d/api/config/OpenAPIConfig.java
api/src/main/java/gov/cms/ab2d/api/controller/common/StatusCommon.java
api/src/test/java/gov/cms/ab2d/api/controller/common/StatusCommonTest.java

https://jira.cms.gov/browse/AB2D-6305
Added a case to the switch statement in StatusCommon for when a job is in **canceled** status. (Previously this just went to the default case which was returning a 500 error). 
Added a function to get and create a proper response object for when status is **canceled** as outlined in [FHIR bulk data export guidelines]https://build.fhir.org/ig/HL7/bulk-data/export.html
AB2D fails part of Version 0.10.0 of the Inferno [Bulk Data Access Test Kit](https://inferno.healthit.gov/test-kits/bulk-data/) Specificallly, test 2.3.3.02. We get a failure when requesting the status of a job which has been cancled. The test is looking for a 404 response, but we instead return a 500.
To be deployed and tested on IMPL (WIP)

[AB2D-6305] - Implement a fix for job cancel polling response

---

.github/workflows/promote.yml
.github/workflows/release.yml

https://jira.cms.gov/browse/PLT-655
A new workflow to promote images up environments
This is to push out and release our images to all our environments in github actions so we can move away from jenkins.
See run at https://github.com/CMSgov/ab2d/actions/runs/11150069080 for successful promote and deploy.

PLT-655 Add workflows to promote images and release app

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/promote.yml
.github/workflows/push-main.yml
.github/workflows/release.yml

https://jira.cms.gov/browse/PLT-679
Added workflow to trigger bulids on push to main and updated build workflow to push "main" tags to ECR.
We need images we can count on being around for a bit from each to push to main for promotion to prod on release. This allows us to set a lifecycle policy specific to tags with the "main" prefix. 
See runs at https://github.com/CMSgov/ab2d/actions/runs/11195118631, https://github.com/CMSgov/ab2d/actions/runs/11195323158, and https://github.com/CMSgov/ab2d/actions/runs/11202145951 for successful tests of the release and promote workflows. The push-main workflow (and expected tag updates in ECR) must be checked following merge of this PR.

PLT-679 Tag commits to main for promotion

---

api/src/test/java/gov/cms/ab2d/api/controller/AdminAPIMaintenanceModeTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIIntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIUnusualDataTests.java
api/src/test/java/gov/cms/ab2d/api/controller/BulkDataAccessAPIV2IntegrationTests.java
api/src/test/java/gov/cms/ab2d/api/controller/MaintenanceModeAPITests.java
api/src/test/java/gov/cms/ab2d/api/controller/v2/StatusAPIV2Test.java
api/src/test/java/gov/cms/ab2d/api/security/JwtAuthenticationFilterTest.java
coverage/pom.xml
coverage/src/test/java/gov/cms/ab2d/coverage/service/CoverageServiceExceptionTest.java
coverage/src/test/java/gov/cms/ab2d/coverage/service/CoverageServiceImplTest.java
coverage/src/test/resources/application.coverage.properties
worker/src/test/java/gov/cms/ab2d/worker/config/AutoScalingServiceTest.java

https://jira.cms.gov/browse/AB2D-6315
Mocked PropertyService in unit and integration tests
In migrating the AB2D unit and integration tests from Jenkins to GitHub Actions we are still seeing flakiness with the "Cannot access properties service, using default database value" and "Cannot find the property maintenance.mode" errors.
Failed main branch https://github.com/CMSgov/ab2d/actions/runs/11355072772/job/31583682078#step:8:23490
This branch: https://github.com/CMSgov/ab2d/actions/runs/11448554170/job/31852335578

AB2D-6315 address AB2D unit test and integration test issues

---

.github/workflows/promote.yml

[PLT-695](https://jira.cms.gov/browse/PLT-695)
promote workflow updated to  tag prod-test env images with the "ab2d-prod-test" prefix.
The current tagging of ab2d-east-prod and ab2d-east-prod-test images causes issues. ECR lifecycle policies are based on prefixes. Essentially, a policy on the ab2d-east-prod prefix will include ab2d-east-prod-test images in its count and may delete all prod images older than any new prod-test images.
Check Workflow Execution:
Confirm that the workflow ran successfully in GitHub Actions.
Confirm Image Tags:
Go to the Amazon ECR repository in the AWS console.
Verify that the images have new tags (e.g., ab2d-prod-test-latest, ab2d-sbx-latest, etc., depending on the environment).
Run Deployment:
Trigger the deployment pipeline for the environment where this …

PLT-695: Update AB2D prod-test ECR tag to avoid overlap with prod 

---

.github/workflows/promote.yml

[PLT-746](https://jira.cms.gov/browse/PLT-746)
"fi" was added at the end of set environment variable statement
ab2d team is trying to deploy some code to "prod-test" and looks like there are errors with existing code syntax in the. "promote" work flow .
Link to a successful manually trigger
https://github.com/CMSgov/ab2d/actions/runs/11666218254

PLT-746 Fix if statement in "promote" workflow

---

common/pom.xml
job/pom.xml
pom.xml

https://jira.cms.gov/browse/AB2D-6397
- In the parent POM, rename property from `postgres.version` to `postgresql.version` to properly override version defined in `spring-boot-dependencies`.
- Bump postgresql version to 42.7.4 to be consistent with #1412
The postgres version defined by `spring-boot-dependencies` is 42.3.8. Snyk flags this version as vulnerable. 
Modules **common** and **job** override this version to 42.7.3. However, when another module imports one of these modules, Maven does not select this overridden version and instead selects the version defined by `spring-boot-dependencies`.
Running `mvn dependency:tree` on **main** shows different versions being used for different modules. 
On the feature branch, the same version is used across all modules.

Override postgresql version defined by spring-boot-dependencies

---

worker/src/main/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverImpl.java
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageDriverUnitTest.java

- https://jira.cms.gov/browse/AB2D-6418
- https://jira.cms.gov/browse/AB2D-6425
Add details to log message for `coverage period missing or year,month query incorrect` error messages. 
When we receive a Slack notification of a failed job, the relevant details (e.g. coverage month and year) are not present in Splunk. This PR adds those details for debugging purposes. 
Added unit tests that verified additional statements were printed to the logs

Add details for 'coverage period missing or year,month query incorrect' log statements

---

pom.xml
worker/src/test/java/gov/cms/ab2d/worker/processor/coverage/CoverageCheckIntegrationTest.java

Updated integration test for worker

Fix intergration test

---

pom.xml

Reverted bfd to 3.2.0
Revert because of exception
`"Unable to get patient information for S5617 for month 3 and year 2025","logger_name":"gov.cms.ab2d.worker.processor.coverage.CoverageMappingCallable","thread_name":"coveragep-2","level":"ERROR","level_value":40000,"stack_trace":"ca.uhn.fhir.rest.server.exceptions.InvalidRequestException: HTTP 400 Bad Request: Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient/_search] with parameters [[cursor]]\n\tat jdk.internal.reflect.GeneratedConstructorAccessor131.newInstance(Unknown Source)\n\tat `

revert post request

---

.github/workflows/deploy-lambda.yml

https://jira.cms.gov/browse/AB2D-6588
- Add deploy-lamda.yml workflow to run terraform init, plan, apply
- Workflow can also reuse `ab2d-lambdas/publish-lambdas.yml` workflow to build lambdas
- https://github.com/CMSgov/ab2d-lambdas/pull/121
- https://github.com/CMSgov/ab2d-ops/pull/310 
This workflow is migrated from 
- https://jenkins.ab2d.cms.gov/job/AB2D-Ops/job/Terraform/job/Deploy%20Lambda/build?delay=0sec
- https://github.com/CMSgov/ab2d-ops/blob/main/jenkins-files/Jenkinsfile.terraform-lambda
Terraform apply works in dev: https://github.com/CMSgov/ab2d/actions/runs/13910578486/job/38923695969
```
gh workflow run deploy-lambda.yml --ref lambda-tf-workflow -f apply=true -f environment=dev -f ab2dOpsBranch=PLT-939 -f ab2dLambdasBranch=update-publish-lamda-workflow -f …
```

Add deploy lambda workflow

---

.github/workflows/terraform.yml

Adhoc change
This is to address failures on run where prodtest is selected but the account number remains blank.
In our step we use the environment chosen for the account number. However prod and prod-test use the same account number. We have to explicitly say they are using the same account number.
https://github.com/CMSgov/ab2d/actions/runs/13970690678/job/39111416664
the assume steps works fine in the run above. It failed on the backend because we do not deploy api in prod-test

Make sure prod and prodtest use the same account

---

.github/workflows/terraform.yml

https://jira.cms.gov/browse/PLT-907
Added "api" to the list of services
So that deploy will uniformly create images on correct gold ami for all services.
Upon workflow run all services will be based on an AL2023 ami.

[PLT-907] adding api to deploy workflow

---

.github/workflows/deploy.yml

ASG instance refresh step for api and worker deployments added
With the migration from EC2 launch configurations to launch templates, the api and worker autoscaling groups must now have their EC2 instances refreshed after a new version of a launch template is deployed in order for those instances to pick up the new AMI version specified in the new launch template version.
GitHub action workflow

PLT-970: add ASG instance refresh step for api and worker deployments

---

.github/workflows/resources/insert-record.sql

N/A
Update SQL to let the database generate the `id` for the job table using the `job_seq` sequence. Currently the script can generate a duplicate key due to using the wrong sequence. 
Sravanti ran [this job](https://github.com/CMSgov/ab2d/actions/runs/14391862587) in sandbox which failed due to duplicate key exception and noticed the sequence is wrong (`hibernate_sequence` instead of `job_seq`)
Tested in sandbox - job is successful:
https://github.com/CMSgov/ab2d/actions/runs/14407081338

Update SQL for 'start job' workflow

---

scripts/verify-deployment.sh

https://jira.cms.gov/browse/PLT-1038
Update the okta url for idm
https://cmsgov.slack.com/archives/CNVRZ73NF/p1744121296051429?thread_ts=1744054808.021109&cid=CNVRZ73NF
We are having issues with fips mode being enforced and idm not allowing access from our runners because of this.
We want to change the vanity url we're accessing so that we don't run into this issue.
IDM by default doesn't require fips with TLS 1.2. Amazon Linux 2023 uses openssl 3.x.x by default and with this comes with TLS 1.3 and fips enabled.  By switching the vanity URL we access we won't hit the same issue
This has been run and works now
https://github.com/CMSgov/ab2d/actions/runs/14738998143/job/41372081943

PLT-1038 update idm url

---

api/pom.xml

https://jira.cms.gov/browse/AB2D-6625
Updated springdoc-openapi-starter-webmvc-ui from 2.6.0 to 2.8.6

Ab2d-6625/update library

---

.github/workflows/e2e-test-gf.yml

Okta test pdp credentials are similar across any test environment
Okta test PDP credentials are consistent across all test environments. For now, I've hardcoded the 'dev' environment in the paths, since global parameters like `/ab2d/mgmt/okta/sensitive/test-pdd-100-id` or `/ab2d/global/okta/sensitive/test-pdd-100-id` are not yet available in the Parameter Store.
(https://cmsgov.slack.com/archives/CNHDC8HCZ/p1750784019465209?thread_ts=1750778670.552399&cid=CNHDC8HCZ)

Temporary path to okta pdp credentials

---

.github/workflows/e2e-test-gf.yml
ops/services/00-bootstrap/README.md
ops/services/00-bootstrap/main.tf
ops/services/00-bootstrap/tofu.tf
ops/services/00-bootstrap/values/prod.sops.yaml
ops/services/00-bootstrap/values/test.sops.yaml

https://jira.cms.gov/browse/AB2D-6746
Here, we're introducing a work-in-progress `00-bootstrap` terraservice module that serves AB2D at the AWS Account Level, encoding AB2D's account-level resources in ECR and SSM.
We're also migrating from usage of the unmanaged ssm values for the PDP test credentials to those defined in `00-bootstrap`.
Post greenfield migration.
* manual dispatch of e2e-test-gf.yml ran successfully against `test`
* manual dispatch of e2e-test-gf.yml ran successfully against `sandbox`

AB2D-6746: Encode account level test credentials

---

ops/services/30-lambda/optout-export.tf
ops/services/30-lambda/optout-import.tf

https://jira.cms.gov/browse/AB2D-6825
Fix S3 Object Lookup failures in environments that aren't `test` or `prod` for `30-lambda` by yielding to a `for_each` instead of a `count` meta parameter.
Addressing post greenfield migration issues.
This applies successfully in `dev`, `test`, `sandbox`, and `prod`

AB2D-6825: Fix 30-lambda object lookup failures

---

ops/services/30-lambda/optout-export.tf
ops/services/30-lambda/optout-import.tf

https://jira.cms.gov/browse/PLT-1250
Changed lambda code location tag
ab2d-lambdas repo code moved to ab2d repo
<details>
<summary>Tofu Plan on dev:</summary>
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
<= read (data resources)
OpenTofu will perform the following actions:
<= data "aws_lambda_invocation" "update_database_schema" {
+ function_name = "ab2d-dev-database-management-handler"
+ id            = (known after apply)
+ input         = <<-EOT
{
}
EOT
+ result        = (known after apply)
}
~ resource "aws_lambda_function" "audit" {
id                             = "ab2d-dev-audit"
~ tags                           = {
~ "code" = …
```

[PLT-1250] Correct opt-out and opt-in lambda code tag after move to ab2d from ab2d-lambdas

---

ops/services/10-core/README.md
ops/services/10-core/database.tf

https://jira.cms.gov/browse/PLT-1236
This PR adopts the latest changes based on the PLT-1236 updates, including:
* enables aws_iam_auth for all clusters
* skips redundant final cluster snapshots
* enables copying cluster tags to snapshots
Post-greenfield migration.
This has been applied to all environments without incident and has addressed a handful of findings reported by various controls in security hub, including AWS Foundational Best Practices 1.0.0 `RDS.16`.

PLT-1236 Adopt latest aurora updates

---

.github/workflows/build-deploy.yml
.github/workflows/build.yml
.github/workflows/deploy-lambda.yml
.github/workflows/deploy.yml
.github/workflows/e2e-bfd-test.yml
.github/workflows/e2e-test.yml
.github/workflows/opt-out-export-deploy.yml
.github/workflows/opt-out-export-unit.yml
.github/workflows/opt-out-import-deploy.yml
.github/workflows/opt-out-import-test-integration.yml
.github/workflows/opt-out-import-unit.yml
.github/workflows/opt-out-import-upload-test.yml
.github/workflows/promote.yml
.github/workflows/publish-lambdas.yml
.github/workflows/pull-request.yml
.github/workflows/push-main.yml
.github/workflows/start-job.yml

https://jira.cms.gov/browse/AB2D-6821
- Remove '-gf' from workflow filenames and workflow names
- Minor updates to workflow to include `API/Worker` to differentiate from other workflows (contracts, events)
Now that legacy workflows have been removed, we can rename our greenfield workflows
N/A

AB2D-6821 Rename workflows / remove '-gf' prefix from files and workflow names

---

.github/workflows/unit-integration-test.yml
ops/services/20-microservices/README.md
ops/services/20-microservices/contracts.tf
ops/services/20-microservices/events.tf
ops/services/20-microservices/main.tf
ops/services/20-microservices/properties.tf
ops/services/30-api/README.md
ops/services/30-api/main.tf
ops/services/30-worker/README.md
ops/services/30-worker/main.tf

https://jira.cms.gov/browse/AB2D-6904
This change makes use of the CDAP-managed cluster module instead of directly configuring `aws_ecs_cluster` resources and effectively configures the clusters to use the prescriptive, environment-specific CMK for each cluster.
Post-greenfield migration, post-fargate migration cleanup.
This was applied to `dev` and `test` environments. We encountered some unrelated issues, particularly in `test`, but those have since been remedied. The necessary imports have already been executed which makes this a very low risk change taking effect on the next deployment to `sandbox` and `prod` environments.

AB2D-6904 Encrypt ECS cluster storage with CMK

---

.github/workflows/contracts-sonarqube.yml
.github/workflows/events-sonarqube.yml
events/build.gradle

https://jira.cms.gov/browse/AB2D-6876
- Run tests before SonarQube step for contracts
- Add `junit-platform-launcher` dependency to run tests for events
- Rename contracts + events SonarQube workflows for clarity 
- SonarQube code coverage wasn't being populated. Running tests beforehand fixes that. 
SonarQube code coverage is now being populated for contracts:

AB2D-6876 Fix SonarQube code coverage for contracts

---

ops/services/10-core/main.tf
ops/services/15-web/bucket.tf

https://jira.cms.gov/browse/AB2D-6911
Address SecurityHub findings by implementing lifecycle configuations. See:
- [[S3.13] S3 general purpose buckets should have Lifecycle configurations](https://docs.aws.amazon.com/securityhub/latest/userguide/s3-controls.html#s3-13)
Add lifecycle configuration that transitions non-current objects in these buckets to IA after 30 days.
- **ab2d-\<env\>-website**
- **ab2d-\<env\>-main**
Note that these buckets were created manually. As a result, lifecycle configurations have to be created manually within AWS Console for each environment. 
- **ab2d-\<env\>-opt-out-import-function**
- **ab2d-\<env\>-opt-out-export-function** 
Verified the tofu commands below generated the expected plan for these modules for the **dev** environment.
- 10-core
- 15-web
``` …
```

AB2D-6911 Add S3 lifecycle configuration
